[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
fortran-compiler = "*"
netcdf-fortran = ">=4.6.0"
python = ">=3.12"

[pypi-dependencies]
preserf = { path = ".", editable = true }

[feature.dev.dependencies]
cmake = ">=3.20"
c-compiler = "*"
cxx-compiler = "*"
netcdf4 = ">=1.7.4"
numpy = ">=1.26"

[feature.dev.pypi-dependencies]
fprettify = ">=0.3"
mypy = ">=1.0"
pytest = ">=8.0"
ruff = ">=0.8"

[environments]
default = { features = [], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tasks]
fmt-py = { cmd = ["ruff", "format", "src", "tests"], default-environment = "dev" }
fmt-py-src = { cmd = ["ruff", "format"], default-environment = "dev" }
fmt-f = { cmd = ["fprettify", "--recursive", "src/preserf-fortran"], default-environment = "dev" }
fmt-f-src = { cmd = ["fprettify"], default-environment = "dev" }
fmt = { depends-on = ["fmt-py", "fmt-f"] }
fmt-check = { cmd = ["ruff", "format", "--check", "src", "tests"], default-environment = "dev" }
lint = { cmd = ["ruff", "check", "src", "tests"], default-environment = "dev" }
test = { cmd = ["pytest"], default-environment = "dev" }
test-all = { cmd = ["pytest"], default-environment = "dev" }
typecheck = { cmd = ["mypy", "src"], default-environment = "dev" }
verify = { depends-on = ["fmt-check", "lint", "typecheck", "test"] }
# clean = { cmd = ["rm", "-rf", "build", "dist", "preserf.egg-info"] }